export type AircraftTelemetry = {
  AIRSPEED_INDICATE: number;
  ALTITUDE: string; // formatted with a comma, e.g. "23,624"
  AUTOPILOT_AIRSPEED_HOLD: number;
  AUTOPILOT_AIRSPEED_HOLD_VAR: number;
  AUTOPILOT_ALTITUDE_LOCK: number;
  AUTOPILOT_ALTITUDE_LOCK_VAR: string; // "0"
  AUTOPILOT_APPROACH_HOLD: number;
  AUTOPILOT_ATTITUDE_HOLD: number;
  AUTOPILOT_BACKCOURSE_HOLD: number;
  AUTOPILOT_FLIGHT_DIRECTOR_ACTIVE: number;
  AUTOPILOT_GLIDESLOPE_HOLD: number;
  AUTOPILOT_HEADING_LOCK: number;
  AUTOPILOT_HEADING_LOCK_DIR: number;
  AUTOPILOT_MASTER: number;
  AUTOPILOT_NAV_SELECTED: number;
  AUTOPILOT_PITCH_HOLD: number;
  AUTOPILOT_PITCH_HOLD_REF: number;
  AUTOPILOT_VERTICAL_HOLD: number;
  AUTOPILOT_VERTICAL_HOLD_VAR: number;
  AUTOPILOT_WING_LEVELER: number;
  CABIN_NO_SMOKING_ALERT_SWITCH: number;
  CABIN_SEATBELTS_ALERT_SWITCH: number;
  ELEVATOR_TRIM_PCT: number;
  FLAPS_HANDLE_PERCENT: number;
  FUEL_PERCENTAGE: number;
  GEAR_HANDLE_POSITION: "UP" | "DOWN";
  LATITUDE: number;
  LONGITUDE: number;
  MAGNETIC_COMPASS: number;
  MAGVAR: number;
  RUDDER_TRIM_PCT: number;
  STATUS: "success" | (string & {});
  VERTICAL_SPEED: number;
};
